import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import DynamicLayout from "./DynamicLayout";
import { UserProvider } from "@/app/context/UserContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SolidApp",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico'
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <DynamicLayout>
            {children}
          </DynamicLayout>
        </UserProvider>
      </body>
    </html>
  );
}
