-- COMANDO PARA REINICCIAR UNA O MAS TABLAS Y QUE TENGAN ID 0
BEGIN TRANSACTION;

DELETE FROM tabla1;
DELETE FROM tabla2;

DBCC CHECKIDENT ('tabla1', RESEED, 0);
DBCC CHECKIDENT ('tabla2', RESEED, 0);

COMMIT;