@startuml

class AuthController {
    - authService: AuthService

    + register(dto: RegisterDto): Promise<{ token: string }>
    + login(dto: LoginDto): Promise<{ token: string }>
    + forgotPassword(email): Promise<{ message: string }> 
    + resetPassword(token, newPassword): Promise<{ message: string }> 
}

class AuthService {
    - usuarioService: UsuarioService
    - jwtService: JwtService
    - hashService: HashService
    - emailService: EmailService
    - gestionDetector: GestionDetector
    - invitacionesService: InvitacionesService

    - buildToken(payload: JwtPayload): { token: string }
    - createPayload(id: number, rol: Rol, gestion: GestionTipo | null, gestionId: number | null): JwtPayload
    + register(dto: RegisterDto): Promise<{ token: string }>
    + login(dto: LoginDto): Promise<{ token: string }>
    + forgotPassword(email: string): Promise<{ message: string }>
    + resetPassword(token: string, newPassword: string): Promise<{ message: string }>
}

class LoginDto {
    correo: string
    clave: string
}

class RegisterDto {
    correo: string
    clave: string
    nombre: string
    apellido: string
    documento: string
    token: string
}

enum GestionTipo {
    EMPRESA = 'EMPRESA',
    ORGANIZACION = 'ORGANIZACION',
}

interface JwtPayload {
  sub: number;
  rol: Rol;
  gestion?: GestionTipo | null;
  gestionId?: number | null;
}

AuthController --> AuthService

LoginDto --> AuthService
RegisterDto --> AuthService
GestionTipo --> AuthService
JwtPayload --> AuthService

'Relaciones con otros services
AuthService --> UsuarioService
AuthService --> JwtService
AuthService --> HashService
AuthService --> EmailService
AuthService --> GestionDetector
AuthService --> InvitacionesService

@enduml