@startuml

class UsuarioController {
  - userService: UsuarioService

  + getMiPerfil(req: RequestConUsuario): Promise<ResponseUsuarioDto>
  + updateMiPerfil(dto: UpdateUsuarioDto): Promise<ResponseUsuarioDto>
  + updateMisCredenciales(dto: UpdateCredencialesDto): Promise<{ token: string }>
  + getMisPuntos(req: RequestConUsuario): Promise<{ id: number; puntos: number }>
  + getMisDonaciones(req: RequestConUsuario, page: number, limit: number): Promise<PaginatedUserDonationsResponseDto>
  + donar(req: RequestConUsuario, dto: CreateDonationDto): Promise<ResponseDonationDto> 
  + getMisCuponesCanjeados(req: RequestConUsuario): : Promise<UsuarioBeneficio[]>
  + usarCupon(id: number): Promise<UsuarioBeneficio>
  + canjearCupon(req: RequestConUsuario, cuponId: number, cantidad: number)

  + findAll(page: number, limit: number, search: number): Promise<{ items: ResponseUsuarioDto[]; total: number }>
  + getDonacionesDeUsuario(id: number, page: number, limit: number): Promise<PaginatedUserDonationsResponseDto>
  + deleteUsuario(id: number): Promise<void>
  + restoreUsuario(id: number): Promise<void>
}

class UsuarioService {
  - usuarioRepository: Repository<Usuario>
  - donacionService: DonacionService
  - beneficioService: BeneficioService
  - usuarioBeneficioService: UsuarioBeneficioService
  - hashService: HashService
  - jwtService: JwtService

  + findByEmail(email: string): Promise<Usuario | null>
  + create(dto: CreateUsuarioDto): Promise<ResponseUsuarioDto>
  + getDonaciones(usuarioId: number, page: number, limit: number): Promise<PaginatedUserDonationsResponseDto>
  + donar(usuarioId: number, dto: CreateDonationDto): Promise<ResponseDonationDto> 
  + getMisCuponesCanjeados(usuarioId: number): Promise<UsuarioBeneficio[]>
  + usarCupon(usuarioBeneficioId: number): Promise<UsuarioBeneficio>
  + canjearCupon(usuarioId: number, cuponId: number, cantidad: number): : Promise<{ success: boolean; cantidadCanjeada: number; puntosGastados: number; puntosRestantes: number; stockRestante: number; 
  + updateCredenciales(id: number, dto: UpdateCredencialesDto): Promise<{ token: string }>
  + updateUsuario(id: number, dto: UpdateUsuarioDto): Promise<ResponseUsuarioDto>
  + updatePuntos(id: number, dto: UpdatePuntosDto): Promise<ResponseUsuarioDto>
  + actualizarUltimaConexion(id: number): : Promise<void>
  + getPoints(id: number): Promise<{ id: number; puntos: number }>
  + findPaginated(page: number, limit: number, search: number): : Promise<{ items: ResponseUsuarioDto[]; total: number }>
  + findOne(id: number): Promise<ResponseUsuarioDto> 
  + delete(id: number): Promise<void>
  + restore(id: number): Promise<void> 
  + mapToResponseDto(usuario: Usuario): ResponseUsuarioDto
  + findByResetToken(token: string) : Promise<Usuario | null>
  + setResetToken(id: number, token: string, expires: Date): Promise<void>
  + clearResetToken(id: number): Promise<void> 
  + resetPassword(id: number, newHashedPassword: string): Promise<void>
}

class EmpresaController {
  - empresasService: EmpresaService

  + findPaginated(page: number, limit: number, search: number, enabled: number): Promise<{ items: EmpresaResponseDTO[]; total: number }> 
  + getDatosEmpresa(req: RequestConUsuario): Promise<EmpresaResponseDTO> 
  + registrarEmpresa(dto: CreateEmpresaDTO): Promise<EmpresaResponseDTO>
  + updateMiPerfil(req: RequestConUsuario, : Express.Multer.File, data: string): : Promise<EmpresaResponseDTO> 
  + getMisCupones(req: RequestConUsuario, page: number, limit: number): Promise<PaginatedBeneficiosResponseDTO> 
  + createCupon(req: RequestConUsuario, dto: CreateBeneficiosDTO): Promise<BeneficiosResponseDTO>
  + updateCupon(cuponId: number, dto: UpdateBeneficiosDTO, req: RequestConUsuario): Promise<BeneficiosResponseDTO>
  + delete(id: number): Promise<void> 
  + restore(id: number): Promise<void>
}

class EmpresaService {
    - empresaRepository: Repository<Empresa>
    - empresaUsuarioRepository: Repository<EmpresaUsuario>
    - beneficioService: BeneficioService
    - dataSource: DataSource
    - hashService: HashService
    - invitacionesService: InvitacionesService

    + findPaginated(page: number, limit: number, search: string, onlyEnabled: boolean): Promise<{ items: EmpresaResponseDTO[]; total: number }>
    + getEmpresaByUsuario(usuarioId: number): Promise<EmpresaResponseDTO>
    + getCupones(usuarioId: number, page: number, limit: number): Promise<PaginatedBeneficiosResponseDTO>
    + createCupon(usuarioId: number, dto: CreateBeneficiosDTO): Promise<BeneficiosResponseDTO>
    + updateCupon(cuponId: number, dto: UpdateBeneficiosDTO , usuarioId: number): Promise<BeneficiosResponseDTO>
    + registrarEmpresa(dto: CreateEmpresaDTO): Promise<EmpresaResponseDTO> 
    + update(usuarioId: number, updateDto: UpdateEmpresaDTO): Promise<EmpresaResponseDTO>
    + verify(id: number): Promise<EmpresaResponseDTO>
    + delete(id: number): Promise<void>
    + restore(id: number): Promise<void>
    - mapToResponseDto(empresa: Empresa): EmpresaResponseDTO
}

class OrganizacionController {
    - organizacionService: OrganizacionService
    
    + getMiPerfil(req: RequestConUsuario): Promise<ResponseOrganizacionDto>
    + getMisCampanas(req: RequestConUsuario, page: number, limit: number): : Promise<ResponseCampaignsDetailPaginatedDto> 
    + registrarOrganizacion(dto: CreateOrganizacionDto): Promise<ResponseOrganizacionDto> 
    + createMiCampaign(req: RequestConUsuario, createCampaignsDto: CreateCampaignsDto, files: Express.Multer.File[]): Promise<ResponseCampaignsDto>
    + updateMiCampaign(campaignId: number, req: RequestConUsuario, updateCampaignsDto: UpdateCampaignsDto, files: Express.Multer.File[]): : Promise<ResponseCampaignsDto> 
    + getMisDonaciones(req: RequestConUsuario, page: number, limit: number, search: string): Promise<PaginatedOrganizationDonationsResponseDto>
    + actualizarEstadoDonacion(id: number, dto: UpdateDonacionEstadoDto, req: RequestConUsuario): : Promise<ResponseDonationDto> 
    + updateMiPerfil(req: RequestConUsuario, updateDto: UpdateOrganizacionDto): Promise<ResponseOrganizacionDto> 
    + findPaginated(page: number, limit: number, search: string): Promise<ResponseOrganizationPaginatedDto>
    + update(id: number, dto: UpdateOrganizacionDto): Promise<ResponseOrganizacionDto> 
    + delete(id: number): Promise<void> 
    + restore(id: number): Promise<void> 
}

class OrganizacionService {
    - organizacionRepository: Repository<Organizacion>
    - organizacionUsuarioRepository: Repository<OrganizacionUsuario>
    - campaignService: CampaignService
    - donacionService: DonacionService
    - hashService: HashService
    - dataSource: DataSource
    - invitacionesService: InvitacionesService

    + findPaginated(page: number, limit: number, search: string): Promise<{ items: ResponseOrganizacionDto[]; total: number }>
    + getOrganizacionByUsuario(usuarioId: number): Promise<Organizacion>
    + findById(id: number): Promise<Organizacion>
    + getCampaigns(id: number, page: number, limit: number): Promise<ResponseCampaignsDetailPaginatedDto>
    + getDonaciones(organizacionId: number, page: number, limit: number, search: string): Promise<PaginatedOrganizationDonationsResponseDto>
    + confirmarDonacion(id: number, dto: UpdateDonacionEstadoDto , gestorId: number): Promise<ResponseDonationDto>
    + createCampaign(id: number, dto: CreateCampaignsDto, imagenes: string[], usuarioId: number): Promise<ResponseCampaignsDto>
    + updateCampaign(id: number, campaignId: number, updateDto: UpdateCampaignsDto, usuarioId: number, imagenes: string[]): Promise<ResponseCampaignsDto>
    + registrarOrganizacion(dto: CreateOrganizacionDto): Promise<ResponseOrganizacionDto>
    + update(dto: UpdateOrganizacionDto, usuarioId: number): Promise<ResponseOrganizacionDto>
    + verify(id: number): Promise<ResponseOrganizacionDto>
    + delete(id: number): Promise<void>
    + restore(id: number): Promise<void>
    - mapToResponseDto(organizacion: Organizacion): ResponseOrganizacionDto
}

class AuthController {
    - authService: AuthService

    + register(dto: RegisterDto): Promise<{ token: string }>
    + login(dto: LoginDto): Promise<{ token: string }>
    + forgotPassword(email): Promise<{ message: string }> 
    + resetPassword(token, newPassword): Promise<{ message: string }> 
}

class AuthService {
    - usuarioService: UsuarioService
    - jwtService: JwtService
    - hashService: HashService
    - emailService: EmailService
    - gestionDetector: GestionDetector
    - invitacionesService: InvitacionesService

    - buildToken(payload: JwtPayload): { token: string }
    - createPayload(id: number, rol: Rol, gestion: GestionTipo | null, gestionId: number | null): JwtPayload
    + register(dto: RegisterDto): Promise<{ token: string }>
    + login(dto: LoginDto): Promise<{ token: string }>
    + forgotPassword(email: string): Promise<{ message: string }>
    + resetPassword(token: string, newPassword: string): Promise<{ message: string }>
}

class HashService {
    + hash(value: string): Promise<string>
    + compare(value: string, hash: string): Promise<boolean>
}

class GestionDetector {
    - empresaStrategy: EmpresaGestionStrategy,
    - organizacionStrategy: OrganizacionGestionStrategy,

    + detectar(usuarioId): Promise<GestionInfo | null>
}

class EmpresaGestionStrategy {
    - empresaUsuarioRepository: Repository<EmpresaUsuario>

    + detectar(usuarioId): Promise<GestionInfo | null>
}

class OrganizacionGestionStrategy {
    - organizacionUsuarioRepository: Repository<OrganizacionUsuario>

    + detectar(usuarioId): Promise<GestionInfo | null>
}

class InvitacionesController {
    - InvitacionesService: InvitacionesService

    + crearInvitacionesEmpresa(empresaId: number, dto: CreateInvitacionDto, req: RequestConUsuario): : Promise<{ invitaciones: Invitacion[]; correosExistentes: string[]; correosYaInvitados: string[]>}
    + getInvitacionesEmpresa(empresaId: number, page: number, limit: number): Promise<{ items: Invitacion[]; total: number;}>
    + crearInvitacionesOrganizacion(organizacionId: number, dto: CreateInvitacionDto, req: RequestConUsuario,): 
    + invitarEntidad(dto: CreateInvitacionDto, req: RequestConUsuario): Promise<{ invitaciones: Invitacion[]; correosExistentes: string[] }>
    + getInvitacionesEntidad(page: number, limit: number): : Promise<{ items: Invitacion[]; total: number; }>
    + getInvitacionesOrganizacion(organizacionId: number, page: number, limit: number): Promise<{ items: Invitacion[]; total: number; }>
    + validarToken(token: string): Promise<{ valido: boolean; correo: string; empresaId?: number; organizacionId?: number; rol: RolSecundario; }> 

}

class InvitacionesService {
    - invitacionRepository: Repository<Invitacion>
    - contactoRepository: Repository<Contacto>
    - empresaUsuarioRepository: Repository<EmpresaUsuario>
    - organizacionUsuarioRepository: Repository<OrganizacionUsuario>
    - emailService: EmailService

    + crearInvitacionesEmpresa(correos: string[], empresaId: number, usuarioInvitadorId: number): Promise<{ invitaciones: Invitacion[]; correosExistentes: string[]; correosYaInvitados: string[];
    + crearInvitacionesOrganizacion(correos: string[], organizacionId: number, usuarioInvitadorId: number)
    + invitarEntidad(correos: string[], usuarioInvitadorId: number)

    + listarInvitacionesEntidad(page: number, limit: number): Promise<{ items: Invitacion[]; total: number; }>
    + listarInvitacionesEmpresa(empresaId: number, page: number, limit: number): Promise<{ items: Invitacion[]; total: number; }> 
    + listarInvitacionesOrganizacion(organizacionId: number, page: number, limit: number): Promise<{ items: Invitacion[]; total: number; }>

    + validarToken(token: string): : Promise<{ correo: string; organizacionId?: number; empresaId?: number; rol: RolSecundario; }>
    + validarInvitacion(token: string, correo: string): Promise<Invitacion>

    - buscarPorToken(token: string): Promise<Invitacion | null>

    + agregarUsuarioAOrganizacion(usuarioId: number, organizacionId: number): Promise<OrganizacionUsuario>
    + agregarUsuarioAEmpresa(usuarioId: number, empresaId: number): Promise<EmpresaUsuario>

    + marcarAceptada(invitacionId: number, usuarioId: number, manager?: EntityManager): Promise<Invitacion>

    - procesarInvitacion(correo: string, datos: Partial<Invitacion>, diasExpiracion: number): Promise<ResultadoProcesamiento>
}

class BeneficioController {
    - beneficiosService: BeneficioService

    + findAllPaginated(page: number, limit: number, search: number, onlyEnabled: boolean): Promise<{ items: BeneficiosResponseDTO[]; total: number; }>
    + findByEmpresaPaginated(idEmpresa: number, page: number, limit: number): Promise<PaginatedBeneficiosResponseDTO> 
    + canjear(id: number, req: RequestConUsuario, dto: CanjearBeneficioDto): Promise<{ success: boolean; cantidadCanjeada: number; puntosGastados: number; puntosRestantes: number; stockRestante: number; }> 
    + updateEstado(id: number, estado: BeneficioEstado, req: RequestConUsuario): Promise<BeneficiosResponseDTO> 
}

class BeneficioService {
    - beneficiosRepository: Repository<Beneficios>
    - empresasRepository: Repository<Empresa>
    - dataSource: DataSource

    + findAllPaginated(page: number, limit: number, search: string, onlyEnabled: boolean): Promise<PaginatedBeneficiosResponseDTO>
    + findByEmpresaPaginated(idEmpresa: number, page: number, limit: number): Promise<PaginatedBeneficiosResponseDTO>
    + create(dto: CreateBeneficiosDTO, usuarioId: number): Promise<BeneficiosResponseDTO>
    + canjear(beneficioId: number, userId: number, cantidad: number): Promise<{ success: boolean; cantidadCanjeada: number; puntosGastados: number; puntosRestantes: number; stockRestante: number; }>
    + update(id: number, dto:UpdateBeneficiosDTO , usuarioId: number): Promise<BeneficiosResponseDTO>
    + updateEstado(id: number, estado: BeneficioEstado, usuarioId: number, rol: Rol): Promise<BeneficiosResponseDTO>
    - validateBeneficioData(data: UpdateBeneficiosDTO): void
    - mapToResponseDto(beneficio: Beneficios): BeneficiosResponseDTO
}

class UsuarioBeneficioService {
    - usuarioBeneficioRepo: Repository<UsuarioBeneficio>

    - validarBeneficio(registro: UsuarioBeneficio | null): asserts registro is UsuarioBeneficio
    + getByUsuario(usuarioId: number): Promise<UsuarioBeneficio[]>
    + usarBeneficio(id: number): Promise<UsuarioBeneficio>
}

class CampaignController {
    - campaignService: CampaignService

    + findPaginated(page: number, limit: number, search: string, onlyEnabled: boolean): Promise<{ items: ResponseCampaignDetalleDto[]; total: number; }>
    + findOneDetail(id: number): Promise<ResponseCampaignDetalleDto>
    + updateEstado(id: number, estado: CampaignEstado): Promise<Campaigns> 
}

class CampaignService {
    - campaignsRepository: Repository<Campaigns>
    - organizacionRepository: Repository<Organizacion>
    - campaignsImagesRepository: Repository<imagenes_campania>


    + findPaginated(page: number, limit: number, search: number, onlyEnabled: boolean): Promise<{ items: ResponseCampaignDetalleDto[]; total: number; }> 
    + findCampaignsPaginated(organizacionId: number, page: number, limit: number): Promise<ResponseCampaignsDetailPaginatedDto> 
    + findOneDetail(id: number): Promise<ResponseCampaignDetalleDto> 
    + create(id: number, createDto: CreateCampaignsDto, imagenes: string[], usuarioId: number): Promise<ResponseCampaignsDto>
    + update(organizacionId: number, campaignId: number, updateDto: UpdateCampaignsDto, usuarioId: number, imagenes: string[]): Promise<ResponseCampaignsDto>
    + updateEstado(id: number, estado: CampaignEstado): Promise<Campaigns>
    + delete(id: number): : Promise<void>

    - mapToResponseDto(campaign: Campaigns): ResponseCampaignsDto
    - mapToDetailDto(campaign: Campaigns): ResponseCampaignDetalleDto
    - setEstado(inicio: Date, fin: Date): CampaignEstado
    - validarRangoFechas(inicio: Date, fin: Date): void
}

class DonacionService {
    - donacionRepository: Repository<Donaciones>
    - campaignsRepository: Repository<Campaigns>
    - usuarioRepository: Repository<Usuario>
    - rankingService: RankingService

    + findAllPaginatedByOrganizacion(organizacionId: number, page: number, limit: number, search: string): Promise<PaginatedOrganizationDonationsResponseDto> 
    + findAllPaginatedByUser(userId: number, page: number, limit: number): Promise<PaginatedUserDonationsResponseDto>
    + create(usuarioId: number, createDto: CreateDonationDto): Promise<ResponseDonationDto>
    + confirmarDonacion(id: number, dto: UpdateDonacionEstadoDto, gestorId: number): Promise<ResponseDonationDto> 

    - validarTransicion(estadoActual: DonacionEstado, nuevoEstado: DonacionEstado): void
    - validarVentanaReversion(fechaEstado: Date): void
    - aplicarEfectosDeEstado(manager: EntityManager, donacion: Donaciones, nuevoEstado: DonacionEstado): Promise<Campaigns | null>
    - mapToResponseDto(donation: Donaciones): ResponseDonationDto
    - mapToOrganizationDonationsResponse(donation: Donaciones): OrganizationDonationItemDto
    - mapToUserDonationResponse(donation: Donaciones): UserDonationItemDto
}

class EmailService {
    - transporter: Transporter
    - baseUrl: string

    + sendResetPasswordEmail(to: string, token: string): Promise<void>
    + sendInvitationEmail(to: string, token: string): Promise<void>
    + sendEntidadInvitationEmail(to: string, token: string): Promise<void>
}

class RankingController {
    - rankingService: RankingService

    + getTop10(): Promise<RankingDTO[]>
}

class RankingService {
    - puntosRepository: Repository<Ranking>

    + getTop10(): Promise<RankingDTO[]>
    + ajustarPuntos(userId: number, puntos: number, manager: EntityManager): : Promise<void>
}

' Relaciones

UsuarioController --> UsuarioService
EmpresaController --> EmpresaService
OrganizacionController --> OrganizacionService
AuthController --> AuthService
BeneficioController --> BeneficioService
CampaignController --> CampaignService
RankingController --> RankingService

UsuarioService --> usuarioRepository
UsuarioService --> DonacionService
UsuarioService --> BeneficioService
UsuarioService --> UsuarioBeneficioService
UsuarioService --> HashService
UsuarioService --> JwtService

EmpresaService --> empresaRepository
EmpresaService --> empresaUsuarioRepository
EmpresaService --> BeneficioService
EmpresaService --> DataSource
EmpresaService --> HashService
EmpresaService --> InvitacionesService

OrganizacionService --> organizacionRepository
OrganizacionService --> organizacionUsuarioRepository
OrganizacionService --> CampaignService
OrganizacionService --> DonacionService
OrganizacionService --> HashService
OrganizacionService --> DataSource
OrganizacionService --> InvitacionesService

AuthService --> UsuarioService
AuthService --> JwtService
AuthService --> HashService
AuthService --> EmailService 
AuthService --> GestionDetector
AuthService --> InvitacionesService

GestionDetector --> EmpresaGestionStrategy
GestionDetector --> OrganizacionGestionStrategy

InvitacionesService --> invitacionRepository
InvitacionesService --> contactoRepository
InvitacionesService --> empresaUsuarioRepository
Invitaciones --> organizacionUsuarioRepository
Invitaciones --> EmailService

BeneficioService --> beneficiosRepository
BeneficioService --> empresasRepository

UsuarioBeneficioService --> usuarioBeneficioRepo

CampaignService --> campaignsRepository
CampaignService --> organizacionRepository
CampaignService --> campaignsImagesRepository

DonacionService --> donacionRepository
DonacionService --> campaignsRepository
DonacionService --> usuarioRepository
DonacionService --> RankingService 


RankingService --> puntosRepository

@enduml
